name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Check if first time contributor
        id: check-contributor
        uses: actions/github-script@v7
        with:
          script: |
            const { data: contributors } = await github.rest.repos.listContributors({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const isFirstTime = !contributors.some(contributor => 
              contributor.login === context.payload.pull_request.user.login
            );
            
            core.setOutput('is-first-time', isFirstTime);
            core.setOutput('contributor-login', context.payload.pull_request.user.login);
      
      - name: Welcome first time contributor
        if: steps.check-contributor.outputs.is-first-time == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const contributor = '${{ steps.check-contributor.outputs.contributor-login }}';
            
            const welcomeComment = `🎉 Welcome to our project @${contributor}! This is your first contribution and we're excited to have you on board!
            
            ## 🚀 Getting Started
            
            - Make sure your PR follows our [contributing guidelines](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CONTRIBUTING.md)
            - Our team will review your changes and provide feedback
            - Don't hesitate to ask questions if you need help
            
            ## 🏆 First Contribution Badge
            
            Once this PR is merged, you'll get a special "First Contribution" badge on your profile!
            
            Thank you for contributing to open source! 🌟`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: welcomeComment
            });
            
            // Add a special label for first-time contributors
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['first-contribution', 'welcome']
            });
